<Project>
  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- Default version for packable projects only -->
  <PropertyGroup Condition="'$(IsPackable)' != 'false'">
    <Version Condition="'$(Version)' == ''">0.0.0-dev</Version>
  </PropertyGroup>
</Project>
