<Project>
  <PropertyGroup>
    <Version Condition="'$(Version)' == ''">0.0.0-dev</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(Version)</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(Version)</FileVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
